import test from "node:test";
import { assert, chmodSync, Database, existsSync, finish, git, gitPath, join, materialize, mkdirSync, mkdtempSync, plan, readFileSync, remediation, review, rmSync, run, setup, sqliteModule, symlinkSync, tmpdir, writeFileSync } from "./helpers.mjs";

test("unrelated baseline-dirty files do not block new Work", () => {
  const dirty = setup(); try { writeFileSync(join(dirty, "unrelated.txt"), "dirty\n"); assert(materialize(dirty), "unrelated dirty path blocked new Work"); } finally { rmSync(dirty, { recursive: true, force: true }); }
});

test("Close preserves special entries, exact reviewed trees, literal paths, deletions, and no-diff behavior", () => {
  const special = setup(); try { materialize(special); run(special, ["work", "task", "start", "WORK-001", "1"]); writeFileSync(join(special, "binary.bin"), Buffer.from([0, 1, 2, 255])); writeFileSync(join(special, "executable.sh"), "#!/bin/sh\nexit 0\n"); chmodSync(join(special, "executable.sh"), 0o755); symlinkSync("missing-target", join(special, "dangling-link")); run(special, ["work", "task", "done", "WORK-001", "1", "--evidence", "Git identity preserved", "--files", "binary.bin", "executable.sh", "dangling-link"]); finish(special, 2, "two.txt"); review(special, "PASS"); run(special, ["close", "WORK-001", "--message", "special Git entries"]); assert(git(special, ["ls-tree", "HEAD", "binary.bin"]).stdout.includes("100644") && git(special, ["ls-tree", "HEAD", "executable.sh"]).stdout.includes("100755") && git(special, ["ls-tree", "HEAD", "dangling-link"]).stdout.includes("120000"), "Git-native special file identity was not preserved"); } finally { rmSync(special, { recursive: true, force: true }); }
  const exact = setup(); try { materialize(exact); finish(exact, 1, "one.txt"); finish(exact, 2, "two.txt"); review(exact, "PASS", ["--findings", JSON.stringify([{ severity: "low", finding: "minor" }])]); writeFileSync(join(exact, "unrelated.txt"), "unrelated\n"); run(exact, ["close", "WORK-001", "--message", "exact tree"]); assert(git(exact, ["show", "--format=", "--name-only", "HEAD"]).stdout.trim().split("\n").sort().join(",") === "one.txt,two.txt" && existsSync(join(exact, "unrelated.txt")), "Close did not commit the exact PASS-reviewed tree"); } finally { rmSync(exact, { recursive: true, force: true }); }
  const paths = setup(); try { materialize(paths); run(paths, ["work", "task", "start", "WORK-001", "1"]); writeFileSync(join(paths, "space name.txt"), "feature\n"); writeFileSync(join(paths, ":(glob)literal.txt"), "feature\n"); run(paths, ["work", "task", "done", "WORK-001", "1", "--evidence", "exact paths", "--files", "space name.txt", ":(glob)literal.txt"]); finish(paths, 2, "two.txt"); review(paths, "PASS"); run(paths, ["close", "WORK-001", "--message", "literal paths"]); assert(git(paths, ["show", "--format=", "--name-only", "HEAD"]).stdout.includes(":(glob)literal.txt"), "literal pathspec-like filename was not committed"); } finally { rmSync(paths, { recursive: true, force: true }); }
  const deletion = setup(); try { writeFileSync(join(deletion, "delete.txt"), "base\n"); git(deletion, ["add", "delete.txt"]); git(deletion, ["commit", "-m", "deletion base"]); materialize(deletion); run(deletion, ["work", "task", "start", "WORK-001", "1"]); rmSync(join(deletion, "delete.txt")); run(deletion, ["work", "task", "done", "WORK-001", "1", "--evidence", "deletion", "--files", "delete.txt"]); finish(deletion, 2, "two.txt"); review(deletion, "PASS"); run(deletion, ["close", "WORK-001", "--message", "deletion"]); assert(!existsSync(join(deletion, "delete.txt")), "exact deletion was not committed"); } finally { rmSync(deletion, { recursive: true, force: true }); }
  const noDiff = setup(); try { materialize(noDiff); run(noDiff, ["work", "task", "start", "WORK-001", "1"]); run(noDiff, ["work", "task", "done", "WORK-001", "1", "--evidence", "no tracked change"]); run(noDiff, ["work", "task", "start", "WORK-001", "2"]); run(noDiff, ["work", "task", "done", "WORK-001", "2", "--evidence", "no tracked change"]); const before = git(noDiff, ["rev-parse", "HEAD"]).stdout.trim(); review(noDiff, "PASS"); run(noDiff, ["close", "WORK-001", "--message", "no diff"]); const db = new Database(join(noDiff, ".nerv/nerv.db"), { readonly: true }); assert(git(noDiff, ["rev-parse", "HEAD"]).stdout.trim() === before && db.prepare("SELECT commit_hash FROM work_items WHERE ref='WORK-001'").get().commit_hash === null, "no-diff Close manufactured a commit"); db.close(); } finally { rmSync(noDiff, { recursive: true, force: true }); }
});

test("review findings, protected attribution, and verification downgrades remain enforced", () => {
  for (const severity of ["critical", "high", "medium"]) { const repo = setup(); try { materialize(repo); finish(repo, 1, "one.txt"); finish(repo, 2, "two.txt"); const findings = JSON.stringify([{ severity, finding: `${severity} issue` }]); assert(run(repo, ["review", "WORK-001", "--outcome", "PASS", "--summary", "invalid", "--validation-evidence", "full", "--findings", findings], 1).includes("PASS is not permitted"), `${severity} finding did not block PASS`); assert(run(repo, ["review", "WORK-001", "--outcome", "REWORK", "--summary", "missing proposal", "--validation-evidence", "full", "--findings", findings], 1).includes("execution-ready remediation Task"), `${severity} REWORK accepted no proposal`); review(repo, "REWORK", ["--findings", findings, "--remediation-title", "Fix", "--remediation-objective", "Resolve issue", "--remediation-approach", "Change implementation", "--remediation-touchpoints", "src/index.ts", "--remediation-acceptance-criteria", "Issue resolved", "--remediation-validation", "pnpm test"]); run(repo, ["work", "materialize-rework", "WORK-001"]); finish(repo, 3, "fix.txt"); assert(review(repo, "PASS").includes("PASS"), `${severity} remediation did not return to Review`); } finally { rmSync(repo, { recursive: true, force: true }); } }
  const residual = setup(); try { materialize(residual); finish(residual, 1, "one.txt"); finish(residual, 2, "two.txt"); const output = review(residual, "PASS", ["--findings", JSON.stringify([{ severity: "medium", finding: "accepted", accepted_as_residual_risk: true }, { severity: "low", finding: "minor" }])]); assert(output.includes("Residual findings") && output.includes("MEDIUM (accepted residual risk)") && output.includes("LOW") && output.includes("do not block Close"), "accepted medium and low residual findings did not coexist with PASS"); } finally { rmSync(residual, { recursive: true, force: true }); }
  const protectedRepo = setup(); try { writeFileSync(join(protectedRepo, "README.md"), "preexisting change\n"); materialize(protectedRepo); run(protectedRepo, ["work", "task", "start", "WORK-001", "1"]); assert(run(protectedRepo, ["work", "task", "done", "WORK-001", "1", "--evidence", "unsafe", "--files", "README.md"], 1).includes("Baseline-dirty"), "protected baseline path was attributable"); } finally { rmSync(protectedRepo, { recursive: true, force: true }); }
  const nested = setup(); try { mkdirSync(join(nested, "src")); writeFileSync(join(nested, "src", "protected.txt"), "dirty\n"); materialize(nested); run(nested, ["work", "task", "start", "WORK-001", "1"]); assert(run(nested, ["work", "task", "done", "WORK-001", "1", "--evidence", "unsafe", "--files", "src"], 1).includes("Invalid attributable"), "directory attribution swallowed protected path"); writeFileSync(join(nested, "src", "normal.txt"), "feature\n"); assert(run(nested, ["work", "task", "done", "WORK-001", "1", "--evidence", "exact", "--files", "src/normal.txt"], 0).includes("Completed"), "exact nested file was rejected"); } finally { rmSync(nested, { recursive: true, force: true }); }
  const stale = setup(); try { materialize(stale); finish(stale, 1, "one.txt"); finish(stale, 2, "two.txt"); review(stale, "PASS"); writeFileSync(join(stale, "one.txt"), "changed after PASS\n"); assert(run(stale, ["close", "WORK-001", "--message", "stale"], 1).includes("changed after PASS"), "Close accepted a changed PASS fingerprint"); assert(run(stale, ["review", "WORK-001", "--outcome", "REWORK", "--summary", "mutated", "--validation-evidence", "full", ...remediation, "--verification-evidence", "external verification failed"], 1).includes("changed after PASS"), "mutated PASS downgraded to REWORK"); writeFileSync(join(stale, "one.txt"), "feature\n"); const downgrade = review(stale, "REWORK", [...remediation, "--verification-evidence", "external verification failed"]); assert(downgrade.includes("REWORK"), "verification could not downgrade PASS to REWORK"); assert(run(stale, ["review", "WORK-001", "--outcome", "REWORK", "--summary", "again", "--validation-evidence", "full", ...remediation], 1).includes("active Work"), "REWORK was accepted without PASS verification evidence"); } finally { rmSync(stale, { recursive: true, force: true }); }
});

test("Close creates the exact reviewed commit without invoking hooks", () => {
  const repo = setup(); try {
    materialize(repo); finish(repo, 1, "nested path.txt"); finish(repo, 2, "two.txt"); review(repo, "PASS");
    const db = new Database(join(repo, ".nerv/nerv.db"), { readonly: true }); const fingerprint = JSON.parse(db.prepare("SELECT git_fingerprint_json FROM work_reviews ORDER BY id DESC LIMIT 1").get().git_fingerprint_json); const baseline = JSON.parse(db.prepare("SELECT git_baseline_json FROM work_items WHERE ref='WORK-001'").get().git_baseline_json); db.close();
    const hook = join(repo, ".git/hooks/pre-commit"); writeFileSync(hook, "#!/bin/sh\necho hook >> hook-mutated.txt\nexit 1\n"); chmodSync(hook, 0o755); run(repo, ["close", "WORK-001", "--message", "exact identity"]);
    const actual = git(repo, ["rev-parse", "HEAD"]).stdout.trim(); assert(git(repo, ["rev-parse", "HEAD^"]).stdout.trim() === baseline.head && git(repo, ["rev-parse", "HEAD^{tree}"]).stdout.trim() === fingerprint.tree && !existsSync(join(repo, "hook-mutated.txt")) && git(repo, ["log", "-1", "--format=%B"]).stdout.includes("Nerv-Work:") && git(repo, ["log", "-1", "--format=%B"]).stdout.includes("Nerv-Work-Ref: WORK-001"), "exact-tree Close did not create the reviewed commit");
    const closed = new Database(join(repo, ".nerv/nerv.db"), { readonly: true }); assert(closed.prepare("SELECT commit_hash FROM work_items WHERE ref='WORK-001'").get().commit_hash === actual, "Close did not persist actual commit hash"); closed.close();
  } finally { rmSync(repo, { recursive: true, force: true }); }
});

test("Close safely handles Git publication and compensation races", () => {
  const repo = setup(); const bin = mkdtempSync(join(tmpdir(), "nerv-git-race-")); try { materialize(repo); finish(repo, 1, "one.txt"); finish(repo, 2, "two.txt"); review(repo, "PASS"); writeFileSync(join(bin, "git"), `#!/bin/sh\nif [ "$1" = update-ref ] && [ ! -e .git/nerv-race-fired ]; then\n  touch .git/nerv-race-fired\n  ref="$2"; old="$4"\n  external=$(${gitPath} commit-tree "$( ${gitPath} rev-parse "$old^{tree}")" -p "$old" -m "external ref advance")\n  ${gitPath} update-ref "$ref" "$external" "$old"\nfi\nexec ${gitPath} "$@"\n`); chmodSync(join(bin, "git"), 0o755); const before = git(repo, ["rev-parse", "HEAD"]).stdout.trim(); const failed = run(repo, ["close", "WORK-001", "--message", "race"], 1, { PATH: `${bin}:${process.env.PATH}` }); const after = git(repo, ["rev-parse", "HEAD"]).stdout.trim(); assert(failed.includes("publication failed") && after !== before && git(repo, ["diff", "--cached", "--quiet"]).status === 0 && git(repo, ["status", "--porcelain"]).stdout.includes("one.txt"), "initial publication CAS loss mutated Git after external authority advanced"); const db = new Database(join(repo, ".nerv/nerv.db"), { readonly: true }); assert(db.prepare("SELECT status FROM work_items WHERE ref='WORK-001'").get().status === "review", "initial CAS loss closed the Work"); db.close(); } finally { rmSync(bin, { recursive: true, force: true }); rmSync(repo, { recursive: true, force: true }); }
  const durable = setup(); const durableBin = mkdtempSync(join(tmpdir(), "nerv-git-durable-failure-")); try { materialize(durable); finish(durable, 1, "one.txt"); finish(durable, 2, "two.txt"); review(durable, "PASS"); const baseline = git(durable, ["rev-parse", "HEAD"]).stdout.trim(); writeFileSync(join(durableBin, "git"), `#!/bin/sh\nif [ "$1" = update-ref ] && [ ! -e .git/nerv-durable-failure-fired ]; then\n  touch .git/nerv-durable-failure-fired\n  ${gitPath} "$@" || exit $?\n  ${process.execPath} -e "const Database=require('${sqliteModule}'); const db=new Database('.nerv/nerv.db'); db.exec(\\\"CREATE TRIGGER fail_close BEFORE UPDATE ON work_items WHEN NEW.status = 'closed' BEGIN SELECT RAISE(ABORT, 'forced durable Close failure'); END\\\"); db.close()"\n  exit 0\nfi\nexec ${gitPath} "$@"\n`); chmodSync(join(durableBin, "git"), 0o755); const failed = run(durable, ["close", "WORK-001", "--message", "durable failure"], 1, { PATH: `${durableBin}:${process.env.PATH}` }); assert(failed.includes("forced durable Close failure") && git(durable, ["rev-parse", "HEAD"]).stdout.trim() === baseline && git(durable, ["diff", "--cached", "--quiet"]).status === 0 && git(durable, ["status", "--porcelain"]).stdout.includes("one.txt"), "durable Close failure did not safely compensate publication"); const state = new Database(join(durable, ".nerv/nerv.db"), { readonly: true }); assert(state.prepare("SELECT status FROM work_items WHERE ref='WORK-001'").get().status === "review", "successful compensation closed the Work"); state.close(); } finally { rmSync(durableBin, { recursive: true, force: true }); rmSync(durable, { recursive: true, force: true }); }
  const compensation = setup(); const compensationBin = mkdtempSync(join(tmpdir(), "nerv-git-compensation-race-")); try { materialize(compensation); finish(compensation, 1, "one.txt"); finish(compensation, 2, "two.txt"); review(compensation, "PASS"); const boundary = join(compensationBin, "boundary"); writeFileSync(join(compensationBin, "git"), `#!/bin/sh\nif [ "$1" = update-ref ] && [ ! -e .git/nerv-compensation-race-fired ]; then\n  touch .git/nerv-compensation-race-fired\n  ${gitPath} "$@" || exit $?\n  ${process.execPath} -e "const Database=require('${sqliteModule}'); const db=new Database('.nerv/nerv.db'); db.exec(\\\"CREATE TRIGGER fail_close BEFORE UPDATE ON work_items WHEN NEW.status = 'closed' BEGIN SELECT RAISE(ABORT, 'forced durable Close failure'); END\\\"); db.close()"\n  ref="$2"; published="$3"\n  external=$(${gitPath} commit-tree "$( ${gitPath} rev-parse "$published^{tree}")" -p "$published" -m "external ref advance")\n  ${gitPath} update-ref "$ref" "$external" "$published" || exit $?\n  printf '%s\\n%s\\n' "$(${gitPath} rev-parse "$ref")" "$(${gitPath} write-tree)" > "${boundary}"\n  ${gitPath} status --porcelain=v1 -z | base64 >> "${boundary}"\n  exit 0\nfi\nexec ${gitPath} "$@"\n`); chmodSync(join(compensationBin, "git"), 0o755); const failed = run(compensation, ["close", "WORK-001", "--message", "compensation race"], 1, { PATH: `${compensationBin}:${process.env.PATH}` }); const [ref, index, status] = readFileSync(boundary, "utf8").trimEnd().split("\n"); const after = { ref: git(compensation, ["rev-parse", "HEAD"]).stdout.trim(), index: git(compensation, ["write-tree"]).stdout.trim(), status: Buffer.from(git(compensation, ["status", "--porcelain=v1", "-z"]).stdout).toString("base64") }; assert(failed.includes("Git/Nerv consistency failure") && JSON.stringify(after) === JSON.stringify({ ref, index, status }), "failed compensation mutated Git after external authority advanced"); const state = new Database(join(compensation, ".nerv/nerv.db"), { readonly: true }); assert(state.prepare("SELECT status FROM work_items WHERE ref='WORK-001'").get().status === "review", "compensation authority loss closed the Work"); state.close(); } finally { rmSync(compensationBin, { recursive: true, force: true }); rmSync(compensation, { recursive: true, force: true }); }
});
