import test from "node:test";
import { Database, assert, existsSync, finish, join, materialize, plan, readFileSync, remediation, review, rmSync, run, setup, writeFileSync } from "./helpers.mjs";

test("Close requires PASS review", () => {
  const repo = setup(); try { materialize(repo); finish(repo, 1, "one.txt"); finish(repo, 2, "two.txt"); assert(run(repo, ["close", "WORK-001", "--message", "early"], 1).includes("not ready"), "Close did not require PASS"); } finally { rmSync(repo, { recursive: true, force: true }); }
});

test("task transitions, checkpoints, reviews, and rework remain strict", () => {
  const repo = setup(); try {
    const dbPath = join(repo, ".nerv/nerv.db");
    const id = materialize(repo); assert(id, "first Work did not materialize"); const baseline = JSON.parse(new Database(dbPath, { readonly: true }).prepare("SELECT git_baseline_json FROM work_items WHERE ref='WORK-001'").get().git_baseline_json); assert(JSON.stringify(Object.keys(baseline).sort()) === JSON.stringify(["head", "protected_paths", "protected_tree"]) && !("dirty" in baseline), "activation baseline retains obsolete dirty state"); const rejected = run(repo, ["work", "materialize", "--plan", JSON.stringify(plan("second"))], 1); const afterRejected = new Database(dbPath, { readonly: true }); assert(rejected.includes("already open") && afterRejected.prepare("SELECT COUNT(*) AS count FROM work_items").get().count === 1 && afterRejected.prepare("SELECT value FROM metadata WHERE key='next_work_number'").get().value === "2", "open Work materialization was not atomic"); afterRejected.close();
    assert(run(repo, ["work", "task", "start", "WORK-001", "2"], 1).includes("cannot start"), "later pending Task started first"); run(repo, ["checkpoint", "WORK-001", "--summary", "work interruption", "--next-step", "continue"]); run(repo, ["work", "task", "start", "WORK-001", "1"]); run(repo, ["checkpoint", "WORK-001", "--summary", "task interruption", "--task", "1", "--next-step", "continue"]); const recovery = run(repo, ["work", "show", "WORK-001"]); for (const marker of [id, "State: active", "approved intent", "approved goal", "approved scope", "Expected touchpoints: src/database.ts", "Out of scope: Git hardening", "Acceptance criteria: contract persists", "Full validation: pnpm validate", "Task 1: Persist fields [active]", "Objective: Store the plan", "Implementation approach: Use direct columns", "Targeted validation: pnpm test", "ID: 2", "Task: Task 1: Persist fields", "Summary: task interruption", "Next step: continue", "Created at:"]) assert(recovery.includes(marker), `work recovery omitted ${marker}`);
    assert(run(repo, ["checkpoint", "WORK-001", "--summary", "wrong", "--task", "2"], 1).includes("active Work"), "pending Task checkpoint accepted"); assert(run(repo, ["work", "task", "start", "WORK-001", "2"], 1).includes("cannot start"), "second active Task accepted"); writeFileSync(join(repo, "one.txt"), "feature\n"); run(repo, ["work", "task", "done", "WORK-001", "1", "--evidence", "targeted passed", "--files", "one.txt"]); assert(run(repo, ["checkpoint", "WORK-001", "--summary", "done", "--task", "1"], 1).includes("active Work"), "done Task checkpoint accepted"); finish(repo, 2, "two.txt"); assert(review(repo, "REWORK", remediation).includes("REWORK"), "active completed Work did not review"); assert(run(repo, ["work", "materialize", "--plan", JSON.stringify(plan("review blocked"))], 1).includes("already open"), "rework Work allowed another Work"); assert(run(repo, ["review", "WORK-001", "--outcome", "PASS", "--summary", "bad", "--validation-evidence", "full"], 1).includes("active Work"), "Review from rework accepted"); assert(run(repo, ["checkpoint", "WORK-001", "--summary", "bad"], 1).includes("active Work"), "rework checkpoint accepted"); run(repo, ["work", "materialize-rework", "WORK-001"]); finish(repo, 3, "fix.txt"); review(repo, "PASS"); assert(run(repo, ["review", "WORK-001", "--outcome", "PASS", "--summary", "again", "--validation-evidence", "full"], 1).includes("Only REWORK"), "Review from review accepted"); assert(run(repo, ["checkpoint", "WORK-001", "--summary", "bad"], 1).includes("active Work"), "PASS checkpoint accepted"); assert(run(repo, ["work", "materialize", "--plan", JSON.stringify(plan("pass blocked"))], 1).includes("already open"), "PASS Work allowed another Work"); const active = join(repo, ".nerv/agent/active/WORK-001.md"); assert(readFileSync(active, "utf8").includes("task interruption") && !run(repo, ["work", "show", "WORK-001"]).includes("Files:"), "simplified checkpoint recovery is incorrect"); run(repo, ["close", "WORK-001", "--message", "smoke"]); assert(!existsSync(active), "closed Work retained active context"); assert(run(repo, ["review", "WORK-001", "--outcome", "PASS", "--summary", "closed", "--validation-evidence", "full"], 1).includes("active Work"), "Review from closed accepted"); assert(run(repo, ["checkpoint", "WORK-001", "--summary", "closed"], 1).includes("active Work") && !existsSync(active), "closed checkpoint recreated context"); assert(materialize(repo, plan("after close")), "closed Work did not allow a new Work");
  } finally { rmSync(repo, { recursive: true, force: true }); }
});
