import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import Database from "better-sqlite3";
const root = resolve(fileURLToPath(new URL("..", import.meta.url))); const cli = join(root, "dist/index.js"); const temp = mkdtempSync(join(tmpdir(), "nerv-intake-e2e-"));
function run(args, expected = 0) { const result = spawnSync(process.execPath, [cli, ...args], { cwd: temp, encoding: "utf8" }); if (result.status !== expected) throw new Error(`${args.join(" ")}: ${result.stdout}${result.stderr}`); return `${result.stdout}${result.stderr}`; }
function task(id, order) { return { id, title: id, intent: "intent", outcome: "outcome", scope: "scope", dependencies: [], order, risk: "low", runSize: "small" }; }
function plan(kind, revised) { const suffix = revised ? "-v2" : ""; if (kind === 0) return { schemaVersion: 1, rationale: "r", context: "c", units: [{ id: `unit-alone${suffix}`, type: "standalone", justification: "one", tasks: [task(`task-alone${suffix}`, 1)] }], relationships: [] }; if (kind === 1) return { schemaVersion: 1, rationale: "r", context: "c", units: [{ id: `unit-build${suffix}`, type: "new-build", title: "New", justification: "group", tasks: [task(`task-build${suffix}`, 1)] }], relationships: [] }; if (kind === 2) return { schemaVersion: 1, rationale: "r", context: "c", units: [{ id: `unit-a${suffix}`, type: "new-build", title: "A", justification: "a", tasks: [task(`task-a${suffix}`, 1)] }, { id: `unit-b${suffix}`, type: "new-build", title: "B", justification: "b", tasks: [task(`task-b${suffix}`, 2)] }], relationships: [{ from: `unit-a${suffix}`, to: `unit-b${suffix}`, type: "depends", rationale: "order" }] }; return { schemaVersion: 1, rationale: "r", context: "c", units: [{ id: `unit-existing${suffix}`, type: "existing-build", buildId: "BUILD-001", justification: "existing", tasks: [task(`task-existing${suffix}`, 1)] }], relationships: [] }; }
try {
  spawnSync("git", ["init", temp]); run(["init"]); run(["new", "build", "existing"]);
  for (let kind = 0; kind < 4; kind++) { const intake = `INTAKE-00${kind + 1}`; const first = join(temp, `${kind}-v1.json`); const second = join(temp, `${kind}-v2.json`); writeFileSync(first, JSON.stringify(plan(kind, false))); writeFileSync(second, JSON.stringify(plan(kind, true))); run(["intake", "create", `intent ${kind}`]); run(["intake", "context", intake]); run(["intake", "propose", intake, "--input", first]); run(["intake", "review", `${intake}-PROPOSAL-001`, "--action", "changes-requested"]); run(["intake", "propose", intake, "--input", second]); run(["intake", "review", `${intake}-PROPOSAL-002`, "--action", "approved"]); run(["intake", "apply", `${intake}-PROPOSAL-002`, "--dry-run"]); run(["intake", "apply", `${intake}-PROPOSAL-002`]); run(["intake", "apply", `${intake}-PROPOSAL-002`]); }
  const db = new Database(join(temp, ".nerv/nerv.db"), { readonly: true }); if (db.prepare("SELECT COUNT(*) AS count FROM intake_proposals WHERE version = 1 AND status = 'changes_requested'").get().count !== 4 || db.prepare("SELECT COUNT(*) AS count FROM intake_materializations WHERE status = 'complete'").get().count !== 4 || db.prepare("SELECT COUNT(*) AS count FROM runs").get().count !== 0) throw new Error("E2E audit, idempotence, or zero-Run guarantee failed"); db.close();
  console.log("ok - E2E CLI flow covers all four planning forms");
} finally { rmSync(temp, { recursive: true, force: true }); }
