import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import Database from "better-sqlite3";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const cli = join(root, "dist/index.js");
const assert = (value, message) => { if (!value) throw new Error(message); };
function run(cwd, args, expected = 0) { const result = spawnSync(process.execPath, [cli, ...args], { cwd, encoding: "utf8" }); const output = `${result.stdout}${result.stderr}`; if (result.status !== expected) throw new Error(`${args.join(" ")}: ${output}`); return output; }
function git(cwd, args) { return spawnSync("git", args, { cwd, encoding: "utf8" }); }
function setup() { const repo = mkdtempSync(join(tmpdir(), "nerv-smoke-")); git(repo, ["init"]); git(repo, ["config", "user.email", "test@example.com"]); git(repo, ["config", "user.name", "Test"]); writeFileSync(join(repo, "README.md"), "base\n"); git(repo, ["add", "README.md"]); git(repo, ["commit", "-m", "initial"]); run(repo, ["init"]); return repo; }
const plan = (title = "Persist plan") => ({ title, intent: "approved intent", goal: "approved goal", scope: "approved scope", expected_touchpoints: "src/database.ts", out_of_scope: "Git hardening", acceptance_criteria: "contract persists", validation: "pnpm validate", tasks: [{ title: "Persist fields", objective: "Store the plan", implementation_approach: "Use direct columns", expected_touchpoints: "src/repository.ts", acceptance_criteria: "fields round trip", validation: "pnpm smoke" }, { title: "Recover fields", objective: "Expose the plan", implementation_approach: "Render from SQLite", expected_touchpoints: "src/index.ts", acceptance_criteria: "show is complete", validation: "pnpm smoke" }] });
function materialize(repo, value = plan()) { const output = run(repo, ["work", "materialize", "--plan", JSON.stringify(value)]); return /Stable ID: ([0-9a-f-]{36})/.exec(output)?.[1]; }
function finish(repo, position, file) { run(repo, ["work", "task", "start", "WORK-001", String(position)]); writeFileSync(join(repo, file), "feature\n"); run(repo, ["work", "task", "done", "WORK-001", String(position), "--evidence", "targeted passed", "--files", file]); }

{
  const repo = setup(); try {
    const dbPath = join(repo, ".nerv/nerv.db"); const db = new Database(dbPath, { readonly: true });
    const names = db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name").all().map((row) => row.name); const version = db.prepare("SELECT value FROM metadata WHERE key='schema_version'").get().value;
    const workColumns = db.prepare("PRAGMA table_info(work_items)").all().map((row) => row.name); const taskColumns = db.prepare("PRAGMA table_info(tasks)").all().map((row) => row.name); db.close();
    assert(version === "1" && JSON.stringify(names) === JSON.stringify(["checkpoints", "metadata", "sqlite_sequence", "tasks", "work_items", "work_reviews"]), "fresh schema is not the clean v1 baseline");
    assert(workColumns.includes("expected_touchpoints") && workColumns.includes("out_of_scope") && !workColumns.includes("git_base_head") && taskColumns.includes("objective") && taskColumns.includes("implementation_approach") && !taskColumns.includes("scope"), "schema does not match the approved contract");
    assert(!readFileSync(join(root, "src/database.ts"), "utf8").includes("Knowledge") && !readFileSync(join(root, "src/database.ts"), "utf8").includes("canUpgrade"), "legacy schema migration code remains");
    const id = materialize(repo); assert(id, "materialization did not report UUID");
    const show = run(repo, ["work", "show", "WORK-001"]); const active = readFileSync(join(repo, ".nerv/agent/active/WORK-001.md"), "utf8");
    for (const marker of ["approved intent", "approved goal", "approved scope", "src/database.ts", "Git hardening", "Store the plan", "Use direct columns", "src/repository.ts", "fields round trip", "pnpm smoke"]) assert(show.includes(marker), `recovery omitted ${marker}`);
    for (const marker of ["Objective: Store the plan", "Implementation approach: Use direct columns", "Expected touchpoints: src/repository.ts"]) assert(active.includes(marker), `active context omitted ${marker}`);
    const failureDb = new Database(dbPath); failureDb.exec("CREATE TRIGGER fail_task_insert BEFORE INSERT ON tasks WHEN NEW.title = 'Fail inside transaction' BEGIN SELECT RAISE(ABORT, 'forced task insert failure'); END"); failureDb.close(); const failingPlan = { ...plan("failed transaction"), tasks: [{ ...plan().tasks[0], title: "Fail inside transaction" }] }; const failed = run(repo, ["work", "materialize", "--plan", JSON.stringify(failingPlan)], 1); const afterFailure = new Database(dbPath, { readonly: true }); const workCount = afterFailure.prepare("SELECT COUNT(*) AS count FROM work_items").get().count; const taskCount = afterFailure.prepare("SELECT COUNT(*) AS count FROM tasks").get().count; const nextNumber = afterFailure.prepare("SELECT value FROM metadata WHERE key='next_work_number'").get().value; afterFailure.close(); assert(failed.includes("forced task insert failure") && workCount === 1 && taskCount === 2 && nextNumber === "2", "transactional materialization failure left state or consumed a Work reference"); const nextId = materialize(repo, plan("after rollback")); assert(nextId && run(repo, ["work", "show", "WORK-002"]).includes(nextId), "rollback did not preserve the next Work reference");
    finish(repo, 1, "one.txt"); finish(repo, 2, "two.txt"); const checkpointDb = new Database(dbPath); const taskId = checkpointDb.prepare("SELECT id FROM tasks WHERE work_item_id=(SELECT id FROM work_items WHERE ref='WORK-001') AND position=2").get().id; checkpointDb.prepare("INSERT INTO checkpoints (work_item_id,task_id,summary,files,decisions,unresolved_issue,next_step,created_at) VALUES ((SELECT id FROM work_items WHERE ref='WORK-001'),?,?,?,?,?,?,?)").run(taskId, "resume", "one.txt,two.txt", "keep direct fields", "none", "review", "2026-01-01T00:00:00.000Z"); checkpointDb.close(); const recovered = run(repo, ["work", "show", id]); for (const marker of ["Completion validation evidence: targeted passed", "ID: 1", "Task: Task 2: Recover fields", "Summary: resume", "Files: one.txt,two.txt", "Decisions: keep direct fields", "Unresolved issue: none", "Next step: review", "Created at: 2026-01-01T00:00:00.000Z"]) assert(recovered.includes(marker), `checkpoint recovery omitted ${marker}`);
    run(repo, ["review", "WORK-001", "--outcome", "PASS", "--summary", "complete", "--validation-evidence", "full", "--findings", JSON.stringify([{ severity: "low", finding: "minor" }])]); const reviewRecovery = run(repo, ["work", "show", "WORK-001"]); for (const marker of ["Latest review:", "ID: 1", "Outcome: PASS", "Summary: complete", "LOW", "Validation evidence: full", "Created at:"]) assert(reviewRecovery.includes(marker), `Review recovery omitted ${marker}`);
    assert(run(repo, ["close", "WORK-001", "--message", "smoke"]).includes("Closed WORK-001"), "selective Close regression"); assert(!existsSync(join(repo, ".nerv/agent/active/WORK-001.md")), "closed Work retained active context");
  } finally { rmSync(repo, { recursive: true, force: true }); }
}
{
  for (const severity of ["critical", "high", "medium"]) {
    const repo = setup(); try { materialize(repo); finish(repo, 1, "one.txt"); finish(repo, 2, "two.txt"); const findings = JSON.stringify([{ severity, finding: `${severity} issue` }]); assert(run(repo, ["review", "WORK-001", "--outcome", "PASS", "--summary", "invalid", "--validation-evidence", "full", "--findings", findings], 1).includes("PASS is not permitted"), `${severity} finding did not block PASS`); assert(run(repo, ["review", "WORK-001", "--outcome", "REWORK", "--summary", "missing proposal", "--validation-evidence", "full", "--findings", findings], 1).includes("execution-ready remediation Task"), `${severity} REWORK accepted no proposal`); run(repo, ["review", "WORK-001", "--outcome", "REWORK", "--summary", "needs fix", "--validation-evidence", "full", "--findings", findings, "--remediation-title", "Fix", "--remediation-objective", "Resolve issue", "--remediation-approach", "Change implementation", "--remediation-touchpoints", "src/index.ts", "--remediation-acceptance-criteria", "Issue resolved", "--remediation-validation", "pnpm smoke"]); run(repo, ["work", "materialize-rework", "WORK-001", "--tasks", JSON.stringify([{ title: "Fix", objective: "Resolve issue", implementation_approach: "Change implementation", expected_touchpoints: "src/index.ts", acceptance_criteria: "Issue resolved", validation: "pnpm smoke" }])]); finish(repo, 3, "fix.txt"); assert(run(repo, ["review", "WORK-001", "--outcome", "PASS", "--summary", "fixed", "--validation-evidence", "full"]).includes("PASS"), `${severity} remediation did not return to Review`); } finally { rmSync(repo, { recursive: true, force: true }); }
  }
  const repo = setup(); try { materialize(repo); finish(repo, 1, "one.txt"); finish(repo, 2, "two.txt"); const residual = JSON.stringify([{ severity: "medium", finding: "accepted", accepted_as_residual_risk: true }, { severity: "low", finding: "minor" }]); assert(run(repo, ["review", "WORK-001", "--outcome", "PASS", "--summary", "residual", "--validation-evidence", "full", "--findings", residual]).includes("Residual findings"), "accepted medium and low findings did not coexist with PASS"); } finally { rmSync(repo, { recursive: true, force: true }); }
}
{
  const repo = setup(); try { materialize(repo); finish(repo, 1, "one.txt"); finish(repo, 2, "two.txt"); assert(run(repo, ["close", "WORK-001", "--message", "early"], 1).includes("not ready"), "Close did not require PASS and validation"); run(repo, ["review", "WORK-001", "--outcome", "PASS", "--summary", "complete", "--validation-evidence", "full"]); writeFileSync(join(repo, "unrelated.txt"), "unrelated\n"); assert(run(repo, ["close", "WORK-001", "--message", "unsafe"], 1).includes("unattributed"), "selective Close accepted unrelated changes"); } finally { rmSync(repo, { recursive: true, force: true }); }
}
{
  const repo = setup(); try { writeFileSync(join(repo, "README.md"), "preexisting change\n"); materialize(repo); run(repo, ["work", "task", "start", "WORK-001", "1"]); writeFileSync(join(repo, "README.md"), "base\n"); run(repo, ["work", "task", "done", "WORK-001", "1", "--evidence", "restored", "--files", "README.md"]); run(repo, ["work", "task", "start", "WORK-001", "2"]); run(repo, ["work", "task", "done", "WORK-001", "2", "--evidence", "verified", "--files", "README.md"]); run(repo, ["review", "WORK-001", "--outcome", "PASS", "--summary", "no diff", "--validation-evidence", "full"]); const count = git(repo, ["rev-list", "--count", "HEAD"]).stdout.trim(); assert(run(repo, ["close", "WORK-001", "--message", "no diff"]).includes("no tracked Git diff") && git(repo, ["rev-list", "--count", "HEAD"]).stdout.trim() === count, "legitimate no-diff Close created a commit"); } finally { rmSync(repo, { recursive: true, force: true }); }
}
{
  const repo = setup(); try { const db = new Database(join(repo, ".nerv/nerv.db")); db.prepare("UPDATE metadata SET value='2' WHERE key='schema_version'").run(); db.close(); assert(run(repo, ["init"], 1).includes("unsupported generated schema"), "previous schema was accepted or migrated"); } finally { rmSync(repo, { recursive: true, force: true }); }
}
{
  const publicSkill = readFileSync(join(root, ".agents/skills/nerv/SKILL.md"), "utf8"); const developmentSkill = readFileSync(join(root, ".agents/skills/nerv-development/SKILL.md"), "utf8");
  assert(publicSkill.includes("atomically materializing") && developmentSkill.includes("atomic approved-plan persistence") && !publicSkill.includes("Task scopes"), "skills retain obsolete approval vocabulary");
  const marker = publicSkill.match(/^nerv_managed_sha256: "([a-f0-9]{64})"$/m); assert(marker && marker[1] === createHash("sha256").update(publicSkill.replace(marker[0], "nerv_managed_sha256: \"\"")).digest("hex"), "public skill managed hash is invalid");
}
console.log("ok - clean persistence smoke coverage");
