import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import Database from "better-sqlite3";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const cli = join(root, "dist/index.js");
function assert(value, message) { if (!value) throw new Error(message); }
function run(cwd, args, expected = 0) { const result = spawnSync(process.execPath, [cli, ...args], { cwd, encoding: "utf8" }); const output = `${result.stdout}${result.stderr}`; if (result.status !== expected) throw new Error(`${args.join(" ")} expected ${expected}: ${output}`); return output; }
function setup() { const repo = mkdtempSync(join(tmpdir(), "nerv-vnext-")); spawnSync("git", ["init"], { cwd: repo }); spawnSync("git", ["config", "user.email", "test@example.com"], { cwd: repo }); spawnSync("git", ["config", "user.name", "Test"], { cwd: repo }); writeFileSync(join(repo, "README.md"), "base\n"); spawnSync("git", ["add", "README.md"], { cwd: repo }); spawnSync("git", ["commit", "-m", "initial"], { cwd: repo }); run(repo, ["init"]); return repo; }
function createWork(repo, title = "Smoke work") { run(repo, ["work", "create", title, "--intent", "intent", "--goal", "goal", "--scope", "scope", "--acceptance-criteria", "criteria", "--validation", "pnpm validate"]); run(repo, ["work", "add-task", "WORK-001", "Implement", "--scope", "scope", "--acceptance-criteria", "criteria", "--validation", "targeted"]); run(repo, ["work", "activate", "WORK-001"]); }
{
  const repo = setup(); try {
    assert(run(repo, ["init"]).includes("already initialized"), "init is not idempotent");
    const db = new Database(join(repo, ".nerv/nerv.db"), { readonly: true }); const tables = new Set(db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map((row) => row.name)); assert(["metadata", "work_items", "tasks", "work_reviews", "checkpoints", "knowledge"].every((name) => tables.has(name)), "fresh vNext schema missing table"); assert(!tables.has("runs") && !tables.has("builds") && !tables.has("intakes"), "legacy schema survived"); db.close(); assert(!existsSync(join(repo, ".nerv/agent/runs")) && !existsSync(join(repo, ".nerv/agent/builds")), "legacy artifacts were initialized");
    run(repo, ["product"]); run(repo, ["repo"]); assert(existsSync(join(repo, ".nerv/product/product.md")) && existsSync(join(repo, ".nerv/repo/development.md")), "canonical context was not preserved");
    createWork(repo); run(repo, ["work", "create", "Future work", "--intent", "i", "--goal", "g", "--scope", "s", "--acceptance-criteria", "a", "--validation", "v"]); assert(run(repo, ["work", "status", "WORK-002"]).includes("State: planned"), "future Work Item was not planned"); assert(existsSync(join(repo, ".nerv/agent/active/WORK-001.md")), "active context missing");
    run(repo, ["task", "start", "TASK-001"]); writeFileSync(join(repo, "feature.txt"), "feature\n"); run(repo, ["task", "done", "TASK-001", "--evidence", "target passed", "--files", "feature.txt"]); run(repo, ["checkpoint", "WORK-001", "--summary", "ready", "--next-step", "review"]); assert(run(repo, ["work", "status", "WORK-001"]).includes("Next:") && readFileSync(join(repo, ".nerv/agent/active/WORK-001.md"), "utf8").includes("ready"), "checkpoint resume state is missing");
    run(repo, ["knowledge", "add", "--type", "discovery", "--title", "FTS check", "--content", "searchable durable observation", "--work", "WORK-001"]); assert(run(repo, ["knowledge", "search", "durable"]).includes("FTS check"), "knowledge search failed"); assert(run(repo, ["knowledge", "show", "1"]).includes("searchable durable observation"), "knowledge retrieval failed");
    run(repo, ["review", "WORK-001", "--outcome", "REWORK", "--summary", "needs check", "--validation-evidence", "full", "--findings", "add check"]); assert(run(repo, ["work", "activate", "WORK-001"], 1).includes("remediation"), "rework activated without remediation"); run(repo, ["work", "add-task", "WORK-001", "Remediate", "--scope", "scope", "--acceptance-criteria", "criteria", "--validation", "targeted"]); run(repo, ["work", "activate", "WORK-001"]); run(repo, ["task", "start", "TASK-002"]); writeFileSync(join(repo, "fix.txt"), "fix\n"); run(repo, ["task", "done", "TASK-002", "--evidence", "target passed", "--files", "fix.txt"]); run(repo, ["review", "WORK-001", "--outcome", "PASS", "--summary", "complete", "--validation-evidence", "pnpm validate"]); run(repo, ["close", "WORK-001", "--message", "implement smoke work"]); assert(!existsSync(join(repo, ".nerv/agent/active/WORK-001.md")), "active context remained after close"); const closed = new Database(join(repo, ".nerv/nerv.db"), { readonly: true }).prepare("SELECT commit_hash FROM work_items WHERE id='WORK-001'").get(); assert(closed?.commit_hash && spawnSync("git", ["rev-list", "--count", "HEAD"], { cwd: repo, encoding: "utf8" }).stdout.trim() === "2", "atomic commit hash was not persisted");
  } finally { rmSync(repo, { recursive: true, force: true }); }
}
{
  const repo = setup(); try { run(repo, ["work", "create", "Blocked work", "--intent", "i", "--goal", "g", "--scope", "s", "--acceptance-criteria", "a", "--validation", "v"]); run(repo, ["work", "add-task", "WORK-001", "First", "--scope", "s", "--acceptance-criteria", "a", "--validation", "v"]); run(repo, ["work", "add-task", "WORK-001", "Second", "--scope", "s", "--acceptance-criteria", "a", "--validation", "v"]); run(repo, ["work", "activate", "WORK-001"]); run(repo, ["task", "start", "TASK-001"]); run(repo, ["task", "block", "TASK-001", "--reason", "missing requirement"]); assert(run(repo, ["work", "status", "WORK-001"]).includes("blocked"), "blocked task is not persisted"); assert(run(repo, ["task", "start", "TASK-002"], 1).includes("blocked"), "blocked execution continued"); } finally { rmSync(repo, { recursive: true, force: true }); }
}
{
  const repo = setup(); try { writeFileSync(join(repo, "shared.txt"), "baseline\n"); createWork(repo); run(repo, ["task", "start", "TASK-001"]); writeFileSync(join(repo, "shared.txt"), "work change\n"); run(repo, ["task", "done", "TASK-001", "--evidence", "ok", "--files", "shared.txt"]); run(repo, ["review", "WORK-001", "--outcome", "PASS", "--summary", "ok", "--validation-evidence", "full"]); assert(run(repo, ["close", "WORK-001", "--message", "must block"], 1).includes("baseline-dirty"), "ambiguous baseline path did not block close"); } finally { rmSync(repo, { recursive: true, force: true }); }
}
{
  const repo = setup(); try { writeFileSync(join(repo, "shared.txt"), "baseline\n"); createWork(repo); run(repo, ["task", "start", "TASK-001"]); writeFileSync(join(repo, "shared.txt"), "unattributed mutation\n"); writeFileSync(join(repo, "feature.txt"), "feature\n"); run(repo, ["task", "done", "TASK-001", "--evidence", "ok", "--files", "feature.txt"]); run(repo, ["review", "WORK-001", "--outcome", "PASS", "--summary", "ok", "--validation-evidence", "full"]); assert(run(repo, ["close", "WORK-001", "--message", "must block"], 1).includes("baseline-dirty path changed"), "unattributed baseline mutation did not block close"); } finally { rmSync(repo, { recursive: true, force: true }); }
}
{
  const repo = setup(); try { writeFileSync(join(repo, "unrelated.txt"), "before\n"); createWork(repo); run(repo, ["task", "start", "TASK-001"]); writeFileSync(join(repo, "feature.txt"), "feature\n"); run(repo, ["task", "done", "TASK-001", "--evidence", "ok", "--files", "feature.txt"]); run(repo, ["review", "WORK-001", "--outcome", "PASS", "--summary", "ok", "--validation-evidence", "full"]); run(repo, ["close", "WORK-001", "--message", "safe close"]); assert(readFileSync(join(repo, "unrelated.txt"), "utf8") === "before\n", "baseline dirty change was modified"); assert(spawnSync("git", ["status", "--short"], { cwd: repo, encoding: "utf8" }).stdout.includes("unrelated.txt"), "baseline dirty change was committed"); } finally { rmSync(repo, { recursive: true, force: true }); }
}
console.log("ok - vNext smoke and E2E coverage");
