#!/usr/bin/env node
import { Command } from "commander";
import { randomUUID } from "node:crypto";
import { createRequire } from "node:module";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { getWorkspaceStatus, ensureWorkspace } from "./workspace.js";
import { openRepository, type Attribution, type Task, type WorkItem } from "./repository.js";
import { scaffoldProductContext, writeProductContext } from "./product.js";
import { generateRepoContext, scaffoldSharedRepoContext } from "./repo-context.js";
import { discoverContext, getSharedKnowledge, searchSharedKnowledge } from "./context.js";
import { nextOperation, removeActiveContext, syncActiveContext } from "./work.js";
import { cachedPaths, captureBaseline, changedPaths, commit, fileState, stage, stagedDiff, validatePath, type GitBaseline } from "./git.js";

const packageVersion = (createRequire(import.meta.url)("../package.json") as { version: string }).version;
const program = new Command().name("nerv").description("Local-first Agent Work Harness.").version(packageVersion);
type Details = { intent: string; goal: string; scope: string; acceptanceCriteria: string; validation: string };
type Workspace = { repoRoot: string; workspaceRoot: string; databasePath: string };
function action(handler: () => void) { try { handler(); } catch (error) { program.error(error instanceof Error ? error.message : String(error), { exitCode: 1, code: "NERV_OPERATION_FAILED" }); } }
function required(options: Record<string, string>, key: keyof Details) { const value = options[key]?.trim(); if (!value) throw new Error(`--${key.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)} is required.`); return value; }
function workspace(): Workspace { const status = getWorkspaceStatus(process.cwd()); if (!status.initialized || !status.repoRoot || !status.workspaceRoot || !status.databasePath) throw new Error("Nerv is not initialized in this repo. Execute `nerv init` first."); return { repoRoot: status.repoRoot, workspaceRoot: status.workspaceRoot, databasePath: status.databasePath }; }
function work(repo: any, reference: string): WorkItem { const item = repo.getWork(reference); if (!item) throw new Error(`Work Item ${reference.toUpperCase()} not found.`); return item; }
function sync(status: Workspace, item: WorkItem) { const repo = openRepository(status.databasePath); try { return syncActiveContext(status.workspaceRoot, item, repo.listTasks(item.id), repo.latestReview(item.id), repo.latestCheckpoint(item.id)); } finally { repo.close(); } }
function recommendedNext(status: Workspace, item: WorkItem) { const repo = openRepository(status.databasePath); try { return nextOperation(item, repo.listTasks(item.id), repo.latestReview(item.id)); } finally { repo.close(); } }
function taskAt(repo: any, item: WorkItem, position: string): Task { const task = repo.getTaskAt(item.id, Number(position)); if (!task || !Number.isInteger(Number(position)) || Number(position) < 1) throw new Error(`Task ${position} not found in ${item.ref}.`); return task; }

program.command("init").action(() => action(() => { const status = getWorkspaceStatus(process.cwd()); if (!status.repoRoot) throw new Error("nerv init must be run inside a Git repository."); const existed = status.initialized; const result = ensureWorkspace(status.repoRoot); console.log(existed ? `Nerv is already initialized in ${status.repoRoot}.` : `Initialized Nerv in ${status.repoRoot}.`); if (result.skillSync.message) console.log(result.skillSync.message); }));
const product = program.command("product").description("Scaffold and update shared Product Context.");
product.action(() => action(() => { const status = workspace(); const result = scaffoldProductContext(status.repoRoot); const repo = openRepository(status.databasePath); try { repo.setMetadata("product_context_updated_at", new Date().toISOString()); } finally { repo.close(); } console.log(`Product Context: ${result.created.length} created, ${result.preserved.length} preserved.`); }));
product.command("write").argument("<document>").requiredOption("--content <content>").action((document: string, options: { content: string }) => action(() => { const status = workspace(); writeProductContext(status.repoRoot, document, options.content); console.log(`Updated Product Context: ${document}`); }));
const repoCommand = program.command("repo").description("Generate local repository observations or scaffold shared facts.");
repoCommand.action(() => action(() => { const status = workspace(); console.log(`Generated ${generateRepoContext(status.repoRoot, status.workspaceRoot)}`); }));
repoCommand.command("scaffold").action(() => action(() => { const status = workspace(); console.log(`Shared Repo Context: ${scaffoldSharedRepoContext(status.repoRoot)}`); }));

const workCommand = program.command("work").description("Deterministic Work Item persistence primitives.");
workCommand.command("create").argument("<title>").requiredOption("--intent <intent>").requiredOption("--goal <goal>").requiredOption("--scope <scope>").requiredOption("--acceptance-criteria <criteria>").requiredOption("--validation <validation>").action((title: string, options: Details) => action(() => { const status = workspace(); const repo = openRepository(status.databasePath); try { const item = repo.createWork({ title, status: "planned", intent: required(options, "intent"), goal: required(options, "goal"), scope: required(options, "scope"), acceptance_criteria: required(options, "acceptanceCriteria"), validation: required(options, "validation") }); console.log(`Created ${item.ref}: ${item.title}`); console.log(`Stable ID: ${item.id}`); console.log(`Recommended next operation: ${nextOperation(item, [], null)}`); } finally { repo.close(); } }));
workCommand.command("add-task").argument("<workRef>").argument("<title>").requiredOption("--scope <scope>").requiredOption("--acceptance-criteria <criteria>").requiredOption("--validation <validation>").action((reference: string, title: string, options: Omit<Details, "intent" | "goal">) => action(() => { const status = workspace(); const repo = openRepository(status.databasePath); try { const item = work(repo, reference); if (!(["planned", "rework"] as string[]).includes(item.status)) throw new Error(`Work Item ${item.ref} must be planned or rework to materialize Tasks.`); const task = repo.createTask({ work_item_id: item.id, title, status: "pending", scope: required(options as Record<string, string>, "scope"), acceptance_criteria: required(options as Record<string, string>, "acceptanceCriteria"), validation: required(options as Record<string, string>, "validation") }); console.log(`Created Task ${task.position} in ${item.ref}.\nRecommended next operation: ${nextOperation(item, repo.listTasks(item.id), repo.latestReview(item.id))}`); } finally { repo.close(); } }));
workCommand.command("activate").argument("<workRef>").action((reference: string) => action(() => { const status = workspace(); let item: WorkItem; const repo = openRepository(status.databasePath); try { item = work(repo, reference); const tasks = repo.listTasks(item.id) as Task[]; if (!(["planned", "rework"] as string[]).includes(item.status) || !tasks.length || (item.status === "rework" && !tasks.some((task) => task.status === "pending"))) throw new Error(`Work Item ${item.ref} cannot be activated without approved pending Tasks.`); if (!item.git_baseline_json) { const baseline = captureBaseline(status.repoRoot); repo.updateWork(item.id, { status: "active", git_base_head: baseline.head, git_baseline_json: JSON.stringify(baseline) }); } else repo.updateWork(item.id, { status: "active" }); item = work(repo, item.id); } finally { repo.close(); } console.log(`Activated ${item!.ref}. Context: ${sync(status, item!)}`); console.log(`Recommended next operation: ${recommendedNext(status, item!)}`); }));
workCommand.command("status").argument("<workRef>").action((reference: string) => action(() => { const status = workspace(); const repo = openRepository(status.databasePath); try { const item = work(repo, reference); const tasks = repo.listTasks(item.id) as Task[]; const review = repo.latestReview(item.id); console.log(`${item.ref}: ${item.title}\nStable ID: ${item.id}\nState: ${item.status}\nTasks: ${tasks.filter((task) => task.status === "done").length}/${tasks.length} done\nLatest review: ${review?.outcome ?? "none"}\nRecommended next operation: ${nextOperation(item, tasks, review)}`); } finally { repo.close(); } }));
workCommand.command("list").action(() => action(() => { const status = workspace(); const repo = openRepository(status.databasePath); try { const items = repo.listWork(); console.log(items.length ? items.map((item: WorkItem) => `${item.ref}: ${item.title} [${item.status}]`).join("\n") : "No Work Items."); } finally { repo.close(); } }));
workCommand.command("show").argument("<workRef>").action((reference: string) => action(() => { const status = workspace(); const repo = openRepository(status.databasePath); try { const item = work(repo, reference); const tasks = repo.listTasks(item.id) as Task[]; console.log(`${item.ref}: ${item.title}\nStable ID: ${item.id}\nState: ${item.status}\nIntent: ${item.intent}\nGoal: ${item.goal}\nScope: ${item.scope}\nAcceptance criteria: ${item.acceptance_criteria}\nValidation: ${item.validation}\n\nTasks:\n${tasks.map((task) => `Task ${task.position}: ${task.title} [${task.status}]`).join("\n") || "None"}`); } finally { repo.close(); } }));
const task = workCommand.command("task").description("Task operations scoped to a Work Item.");
task.command("start").argument("<workRef>").argument("<position>").action((reference: string, position: string) => action(() => transitionTask(reference, position, "start")));
task.command("done").argument("<workRef>").argument("<position>").requiredOption("--evidence <evidence>").requiredOption("--files <paths...>").action((reference: string, position: string, options: { evidence: string; files: string[] }) => action(() => completeTask(reference, position, options)));
task.command("block").argument("<workRef>").argument("<position>").requiredOption("--reason <reason>").action((reference: string, position: string, options: { reason: string }) => action(() => transitionTask(reference, position, "block", options.reason)));

program.command("review").argument("<workRef>").requiredOption("--outcome <PASS|REWORK>").requiredOption("--summary <summary>").requiredOption("--validation-evidence <evidence>").option("--findings <findings>").option("--remediation-title <title>").option("--remediation-objective <objective>").option("--remediation-approach <approach>").option("--remediation-touchpoints <touchpoints>").option("--remediation-acceptance-criteria <criteria>").option("--remediation-validation <validation>").action((reference: string, options: { outcome: string; summary: string; validationEvidence: string; findings?: string; remediationTitle?: string; remediationObjective?: string; remediationApproach?: string; remediationTouchpoints?: string; remediationAcceptanceCriteria?: string; remediationValidation?: string }) => action(() => { const status = workspace(); const repo = openRepository(status.databasePath); let item: WorkItem; let outcome: string; try { item = work(repo, reference); outcome = options.outcome.toUpperCase(); const remediation = [options.remediationTitle, options.remediationObjective, options.remediationApproach, options.remediationAcceptanceCriteria, options.remediationValidation]; if (!(["PASS", "REWORK"] as string[]).includes(outcome) || (outcome === "REWORK" && (!options.findings?.trim() || remediation.some((value) => !value?.trim())))) throw new Error("REWORK requires findings and an execution-ready remediation Task."); if (!(["active", "review"] as string[]).includes(item.status) || (repo.listTasks(item.id) as Task[]).some((entry) => entry.status !== "done")) throw new Error("Work Review requires an active Work Item with every Task done."); repo.createReview({ work_item_id: item.id, outcome, summary: options.summary, findings: options.findings ?? null, validation_evidence: options.validationEvidence }); repo.updateWork(item.id, { status: outcome === "PASS" ? "review" : "rework", validation_evidence: options.validationEvidence }); item = work(repo, item.id); } finally { repo.close(); } sync(status, item!); const remediation = outcome === "REWORK" ? `\nFindings:\n${options.findings!.trim()}\n\nRemediation Plan Preview:\n\nTask 1 — ${options.remediationTitle!.trim()}\n\nObjective:\n${options.remediationObjective!.trim()}\n\nImplementation approach:\n${options.remediationApproach!.trim()}\n${options.remediationTouchpoints?.trim() ? `\nExpected touchpoints:\n${options.remediationTouchpoints.trim()}\n` : ""}\nAcceptance criteria:\n${options.remediationAcceptanceCriteria!.trim()}\n\nTargeted validation:\n${options.remediationValidation!.trim()}\n` : ""; console.log(`${item!.ref} review: ${outcome}${remediation}\nRecommended next operation: ${recommendedNext(status, item!)}`); }));
program.command("checkpoint").argument("<workRef>").requiredOption("--summary <summary>").option("--task <position>").option("--next-step <step>").action((reference: string, options: { summary: string; task?: string; nextStep?: string }) => action(() => { const status = workspace(); const repo = openRepository(status.databasePath); let item: WorkItem; try { item = work(repo, reference); const entry = options.task ? taskAt(repo, item, options.task) : null; repo.createCheckpoint({ work_item_id: item.id, task_id: entry?.id ?? null, summary: options.summary, files: null, decisions: null, unresolved_issue: null, next_step: options.nextStep ?? null }); } finally { repo.close(); } sync(status, item!); console.log(`Checkpoint saved for ${item!.ref}.\nRecommended next operation: ${recommendedNext(status, item!)}`); }));
const knowledge = program.command("knowledge");
knowledge.command("add").requiredOption("--type <type>").requiredOption("--title <title>").requiredOption("--content <content>").option("--work <workRef>").option("--topic <topic>").action((options: any) => action(() => { const status = workspace(); const repo = openRepository(status.databasePath); try { if (!(["decision", "architecture", "discovery", "pattern"] as string[]).includes(options.type)) throw new Error("Knowledge type is invalid."); const item = options.work ? work(repo, options.work) : null; const knowledgeItem = repo.createKnowledge({ type: options.type, title: options.title, content: options.content, work_item_id: item?.id ?? null, topic_key: options.topic ?? null }); console.log(`Knowledge ${knowledgeItem.id} recorded locally.`); } finally { repo.close(); } }));
knowledge.command("search").argument("<query>").action((query: string) => action(() => { const status = workspace(); const repo = openRepository(status.databasePath); try { for (const item of repo.searchKnowledge(query)) console.log(`${item.id}: ${item.title} [${item.type}, local]`); for (const item of searchSharedKnowledge(status.repoRoot, query)) console.log(`${item.ref}: ${item.title} [shared]`); } finally { repo.close(); } }));
knowledge.command("show").argument("<id>").action((id: string) => action(() => { const status = workspace(); if (id.startsWith("shared:")) { const item = getSharedKnowledge(status.repoRoot, id); if (!item) throw new Error(`Knowledge ${id} not found.`); console.log(`${item.ref}: ${item.title}\n\n${item.content}`); return; } const repo = openRepository(status.databasePath); try { const item = repo.getKnowledge(Number(id)); if (!item) throw new Error(`Knowledge ${id} not found.`); console.log(`${item.id}: ${item.title}\n\n${item.content}`); } finally { repo.close(); } }));
knowledge.command("promote").argument("<id>").action((id: string) => action(() => { const status = workspace(); const repo = openRepository(status.databasePath); try { const item = repo.getKnowledge(Number(id)); if (!item) throw new Error(`Knowledge ${id} not found.`); const directory = join(status.repoRoot, ".nerv-context", "knowledge"); mkdirSync(directory, { recursive: true }); const path = join(directory, `${randomUUID()}.md`); writeFileSync(path, `# ${item.title}\n\n${item.content.trim()}\n`, "utf8"); console.log(`Promoted Knowledge ${item.id}: ${path}`); } finally { repo.close(); } }));
program.command("close").argument("<workRef>").requiredOption("--message <message>").action((reference: string, options: { message: string }) => action(() => { closeWork(reference, options.message); console.log("Recommended next operation: No further Nerv lifecycle operation is required."); }));
program.command("status").action(() => action(() => { const status = getWorkspaceStatus(process.cwd()); console.log(`Nerv status: ${status.initialized ? "initialized" : "not initialized"}`); if (status.initialized && status.repoRoot && status.workspaceRoot && status.databasePath) { const context = discoverContext(status.repoRoot, status.workspaceRoot, status.databasePath); console.log(`Product Context: ${context.product.length ? "available" : "not available"}`); console.log(`Shared Repo Context: ${context.repo ? "available" : "not available"}`); console.log(`Local Repo Observations: ${context.localRepo ? "available" : "not available"}`); } }));

function transitionTask(reference: string, position: string, operation: "start" | "block", reason?: string) { const status = workspace(); const repo = openRepository(status.databasePath); let item: WorkItem; let entry: Task; try { item = work(repo, reference); entry = taskAt(repo, item, position); const tasks = repo.listTasks(item.id) as Task[]; if (operation === "start") { if (item.status !== "active" || entry.status !== "pending" || tasks.some((task) => task.status === "active" || task.status === "blocked")) throw new Error(`Task ${entry.position} cannot start.`); repo.updateTask(entry.id, { status: "active" }); } else { if (entry.status !== "active") throw new Error(`Task ${entry.position} must be active.`); repo.updateTask(entry.id, { status: "blocked", block_reason: reason!.trim() }); } item = work(repo, item.id); } finally { repo.close(); } sync(status, item!); console.log(`${operation === "start" ? `Started Task ${entry!.position} in ${item!.ref}.` : `Blocked: Task ${entry!.position} in ${item!.ref}\nReason: ${reason}`}\nRecommended next operation: ${recommendedNext(status, item!)}`); }
function completeTask(reference: string, position: string, options: { evidence: string; files: string[] }) { const status = workspace(); const repo = openRepository(status.databasePath); let item: WorkItem; let entry: Task; try { item = work(repo, reference); entry = taskAt(repo, item, position); if (entry.status !== "active") throw new Error(`Task ${entry.position} must be active.`); const baseline = JSON.parse(item.git_baseline_json ?? "null"); if (!baseline) throw new Error("Task completion requires an activation Git baseline."); const paths = [...new Set(options.files.map((path) => validatePath(status.repoRoot, path)))].sort(); const baselinePaths = new Set(baseline.dirty.map((dirty: { path: string }) => dirty.path)); const ambiguousBaselinePaths = paths.filter((path) => baselinePaths.has(path)); const attribution: Attribution = { paths: paths.map((path) => fileState(status.repoRoot, path)), ambiguousBaselinePaths }; repo.updateTask(entry.id, { status: "done", validation_evidence: options.evidence.trim(), attribution_json: JSON.stringify(attribution) }); item = work(repo, item.id); } finally { repo.close(); } sync(status, item!); console.log(`Completed Task ${entry!.position} in ${item!.ref}.\nRecommended next operation: ${recommendedNext(status, item!)}`); }
function closeWork(reference: string, message: string) {
  const status = workspace();
  const repo = openRepository(status.databasePath);
  try {
    const item = work(repo, reference);
    if (item.status !== "review" || repo.latestReview(item.id)?.outcome !== "PASS" || !item.validation_evidence) throw new Error(`Work Item ${item.ref} is not ready to close.`);
    const baseline = JSON.parse(item.git_baseline_json ?? "null") as GitBaseline | null;
    if (!baseline || (repo.listTasks(item.id) as Task[]).some((task) => task.status !== "done")) throw new Error("Close requires an activated Work Item with all Tasks done.");
    if (cachedPaths(status.repoRoot).length) throw new Error("Close blocked: Git index is not clean.");
    const tasks = repo.listTasks(item.id) as Task[];
    const attributed = new Set<string>();
    const ambiguousBaselinePaths = new Set<string>();
    for (const task of tasks) {
      const attribution = task.attribution_json ? JSON.parse(task.attribution_json) as Attribution : null;
      for (const path of attribution?.paths ?? []) attributed.add(path.path);
      for (const path of attribution?.ambiguousBaselinePaths ?? []) ambiguousBaselinePaths.add(path);
    }
    const changed = changedPaths(status.repoRoot, baseline.head);
    const changedSet = new Set(changed);
    const baselinePaths = new Set(baseline.dirty.map((dirty) => dirty.path));
    const unchangedBaselinePaths = new Set(baseline.dirty.filter((dirty) => {
      const actual = fileState(status.repoRoot, dirty.path);
      return changedSet.has(dirty.path) && actual.state === dirty.state && actual.hash === dirty.hash;
    }).map((dirty) => dirty.path));
    const restoredBaselinePaths = baseline.dirty.filter((dirty) => !changedSet.has(dirty.path)).map((dirty) => dirty.path);
    const noWorkDiff = changed.every((path) => baselinePaths.has(path) && unchangedBaselinePaths.has(path)) && restoredBaselinePaths.every((path) => attributed.has(path) && ambiguousBaselinePaths.has(path));
    if (noWorkDiff) {
      repo.updateWork(item.id, { status: "closed", closed_at: new Date().toISOString(), commit_hash: null });
      removeActiveContext(status.workspaceRoot, item.ref);
      console.log(`Closed ${item.ref}: no tracked Git diff.`);
      return;
    }
    if (ambiguousBaselinePaths.size) throw new Error("Close blocked: baseline-dirty paths cannot be attributed safely.");
    for (const dirty of baseline.dirty) {
      const actual = fileState(status.repoRoot, dirty.path);
      if (actual.state !== dirty.state || actual.hash !== dirty.hash) throw new Error(`Close blocked: baseline-dirty path changed: ${dirty.path}`);
    }
    const unowned = changed.filter((path) => !attributed.has(path) && !baselinePaths.has(path));
    if (unowned.length) throw new Error(`Close blocked: unattributed changes: ${unowned.join(", ")}`);
    stage(status.repoRoot, changed.filter((path) => attributed.has(path)));
    if (!stagedDiff(status.repoRoot)) throw new Error("Close blocked: no attributable changes to commit.");
    const hash = commit(status.repoRoot, `${message}\n\nNerv-Work: ${item.id}\nNerv-Work-Ref: ${item.ref}`);
    repo.updateWork(item.id, { status: "closed", closed_at: new Date().toISOString(), commit_hash: hash });
    removeActiveContext(status.workspaceRoot, item.ref);
    console.log(`Closed ${item.ref}: ${hash}`);
  } finally {
    repo.close();
  }
}
await program.parseAsync();
