#!/usr/bin/env node
import { Command } from "commander";
import { getWorkspaceStatus, ensureWorkspace } from "./workspace.js";
import { openRepository, type Attribution, type Task } from "./repository.js";
import { scaffoldProductContext } from "./product.js";
import { generateRepoContext } from "./repo-context.js";
import { discoverContext } from "./context.js";
import { activePath, nextOperation, removeActiveContext, syncActiveContext } from "./work.js";
import { cachedPaths, captureBaseline, changedPaths, commit, fileState, stage, stagedDiff, validatePath } from "./git.js";

const program = new Command().name("nerv").description("Local-first Agent Work Harness.").version("0.2.0");
type Details = { intent: string; goal: string; scope: string; acceptanceCriteria: string; validation: string };
type InitializedWorkspace = { repoRoot: string; workspaceRoot: string; databasePath: string; initialized: true };
function required(options: Record<string, string>, key: keyof Details) { const value = options[key]?.trim(); if (!value) throw new Error(`--${key.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)} is required.`); return value; }
function workspace(): InitializedWorkspace { const status = getWorkspaceStatus(process.cwd()); if (!status.initialized || !status.repoRoot || !status.databasePath || !status.workspaceRoot) throw new Error("Nerv is not initialized in this repo. Execute `nerv init` first."); return { repoRoot: status.repoRoot, workspaceRoot: status.workspaceRoot, databasePath: status.databasePath, initialized: true }; }
function sync(status: InitializedWorkspace, id: string) { const repo = openRepository(status.databasePath); try { const work = repo.getWork(id)!; return syncActiveContext(status.workspaceRoot, work, repo.listTasks(id), repo.latestReview(id), repo.latestCheckpoint(id)); } finally { repo.close(); } }
function action(handler: () => void) { try { handler(); } catch (error) { program.error(error instanceof Error ? error.message : String(error), { exitCode: 1, code: "NERV_OPERATION_FAILED" }); } }

program.command("init").action(() => action(() => { const status = getWorkspaceStatus(process.cwd()); if (!status.repoRoot) throw new Error("nerv init must be run inside a Git repository."); const existed = status.initialized; ensureWorkspace(status.repoRoot); console.log(existed ? `Nerv is already initialized in ${status.repoRoot}.` : `Initialized Nerv in ${status.repoRoot}.`); }));
program.command("product").description("Scaffold canonical Product Context documents.").action(() => action(() => { const status = workspace(); const result = scaffoldProductContext(status.workspaceRoot); const repo = openRepository(status.databasePath); try { repo.setMetadata("product_context_updated_at", new Date().toISOString()); } finally { repo.close(); } console.log(`Product Context: ${result.created.length} created, ${result.preserved.length} preserved.`); }));
program.command("repo").description("Generate Repo Context.").action(() => action(() => { const status = workspace(); const path = generateRepoContext(status.repoRoot, status.workspaceRoot); const repo = openRepository(status.databasePath); try { repo.setMetadata("repo_context_updated_at", new Date().toISOString()); } finally { repo.close(); } console.log(`Generated ${path}`); }));

const work = program.command("work").description("Deterministic Work Item persistence primitives.");
work.command("create").argument("<title>").requiredOption("--intent <intent>").requiredOption("--goal <goal>").requiredOption("--scope <scope>").requiredOption("--acceptance-criteria <criteria>").requiredOption("--validation <validation>").action((title: string, options: Details) => action(() => { const status = workspace(); const repo = openRepository(status.databasePath); try { const item = repo.createWork({ title, status: "planned", intent: required(options, "intent"), goal: required(options, "goal"), scope: required(options, "scope"), acceptance_criteria: required(options, "acceptanceCriteria"), validation: required(options, "validation") }); console.log(`Created ${item.id}: ${item.title}`); console.log(`Next: ${nextOperation(item, [], null)}`); } finally { repo.close(); } }));
work.command("add-task").argument("<workId>").argument("<title>").requiredOption("--scope <scope>").requiredOption("--acceptance-criteria <criteria>").requiredOption("--validation <validation>").action((workId: string, title: string, options: Omit<Details, "intent" | "goal">) => action(() => { const status = workspace(); const id = workId.toUpperCase(); const repo = openRepository(status.databasePath); try { const item = repo.getWork(id); if (!item || !["planned", "rework"].includes(item.status)) throw new Error(`Work Item ${id} must be planned or rework to materialize Tasks.`); const task = repo.createTask({ work_item_id: id, title, status: "pending", scope: required(options as Record<string, string>, "scope"), acceptance_criteria: required(options as Record<string, string>, "acceptanceCriteria"), validation: required(options as Record<string, string>, "validation") }); console.log(`Created ${task.id} in ${id}.`); } finally { repo.close(); } }));
work.command("activate").argument("<workId>").action((workId: string) => action(() => { const status = workspace(); const id = workId.toUpperCase(); const repo = openRepository(status.databasePath); try { const item = repo.getWork(id); if (!item || !["planned", "rework"].includes(item.status)) throw new Error(`Work Item ${id} cannot be activated.`); const tasks = repo.listTasks(id) as Task[]; if (tasks.length === 0) throw new Error(`Work Item ${id} has no approved Tasks.`); if (item.status === "rework" && !tasks.some((entry: Task) => entry.status === "pending")) throw new Error(`Work Item ${id} requires approved pending remediation Tasks before activation.`); if (!item.git_baseline_json) { const baseline = captureBaseline(status.repoRoot); repo.updateWork(id, { status: "active", git_base_head: baseline.head, git_baseline_json: JSON.stringify(baseline) }); } else repo.updateWork(id, { status: "active" }); } finally { repo.close(); } console.log(`Activated ${id}. Context: ${sync(status, id)}`); }));
work.command("status").argument("<workId>").action((workId: string) => action(() => { const status = workspace(); const id = workId.toUpperCase(); const repo = openRepository(status.databasePath); try { const item = repo.getWork(id); if (!item) throw new Error(`Work Item ${id} not found.`); const tasks = repo.listTasks(id) as Task[]; const review = repo.latestReview(id); console.log(`${item.id}: ${item.title}\nState: ${item.status}\nTasks: ${tasks.filter((task: Task) => task.status === "done").length}/${tasks.length} done\nLatest review: ${review?.outcome ?? "none"}\nNext: ${nextOperation(item, tasks, review)}`); } finally { repo.close(); } }));

const task = program.command("task").description("Deterministic Task transitions.");
task.command("start").argument("<taskId>").action((taskId: string) => action(() => { const status = workspace(); const id = taskId.toUpperCase(); const repo = openRepository(status.databasePath); let workId: string; try { const item = repo.getTask(id); const parent = item ? repo.getWork(item.work_item_id) : null; if (!item || item.status !== "pending" || parent?.status !== "active") throw new Error(`Task ${id} must be pending in an active Work Item.`); const siblings = repo.listTasks(item.work_item_id) as Task[]; if (siblings.some((candidate: Task) => candidate.status === "blocked")) throw new Error(`Work Item ${item.work_item_id} is blocked; do not continue execution.`); if (siblings.some((candidate: Task) => candidate.status === "active")) throw new Error("Only one Task may be active in a Work Item."); repo.updateTask(id, { status: "active" }); workId = item.work_item_id; } finally { repo.close(); } sync(status, workId!); console.log(`Started ${id}.`); }));
task.command("done").argument("<taskId>").requiredOption("--evidence <evidence>").requiredOption("--files <paths...>").action((taskId: string, options: { evidence: string; files: string[] }) => action(() => completeTask(taskId, options, false)));
task.command("block").argument("<taskId>").requiredOption("--reason <reason>").action((taskId: string, options: { reason: string }) => action(() => { const status = workspace(); const id = taskId.toUpperCase(); const repo = openRepository(status.databasePath); let workId: string; try { const item = repo.getTask(id); if (!item || item.status !== "active") throw new Error(`Task ${id} must be active.`); repo.updateTask(id, { status: "blocked", block_reason: options.reason.trim() }); workId = item.work_item_id; } finally { repo.close(); } sync(status, workId!); console.log(`Blocked: ${id}\nReason: ${options.reason}\nNext: nerv work status ${workId!}`); }));

program.command("review").description("Persist a Work Review supplied by an external reasoning workflow.").argument("<workId>").requiredOption("--outcome <PASS|REWORK>").requiredOption("--summary <summary>").requiredOption("--validation-evidence <evidence>").option("--findings <findings>").action((workId: string, options: { outcome: string; summary: string; validationEvidence: string; findings?: string }) => action(() => { const status = workspace(); const id = workId.toUpperCase(); const outcome = options.outcome.toUpperCase(); if (outcome !== "PASS" && outcome !== "REWORK") throw new Error("Review outcome must be PASS or REWORK."); if (outcome === "REWORK" && !options.findings?.trim()) throw new Error("REWORK requires findings and minimum remediation."); const repo = openRepository(status.databasePath); try { const item = repo.getWork(id); if (!item || !["active", "review"].includes(item.status)) throw new Error(`Work Item ${id} cannot be reviewed.`); if ((repo.listTasks(id) as Task[]).some((entry: Task) => entry.status !== "done")) throw new Error("Work Review requires every Task to be done."); repo.createReview({ work_item_id: id, outcome, summary: options.summary, findings: options.findings ?? null, validation_evidence: options.validationEvidence }); repo.updateWork(id, { status: outcome === "PASS" ? "review" : "rework", validation_evidence: options.validationEvidence }); } finally { repo.close(); } sync(status, id); console.log(`${id} review: ${outcome}`); }));

program.command("checkpoint").argument("<workId>").requiredOption("--summary <summary>").option("--task <taskId>").option("--files <files>").option("--decisions <decisions>").option("--unresolved-issue <issue>").option("--next-step <step>").action((workId: string, options: { summary: string; task?: string; files?: string; decisions?: string; unresolvedIssue?: string; nextStep?: string }) => action(() => { const status = workspace(); const id = workId.toUpperCase(); const repo = openRepository(status.databasePath); try { const item = repo.getWork(id); const taskId = options.task?.toUpperCase() ?? null; const taskRecord = taskId ? repo.getTask(taskId) : null; if (!item || item.status === "closed") throw new Error(`Work Item ${id} cannot receive a Checkpoint.`); if (taskId && (!taskRecord || taskRecord.work_item_id !== id)) throw new Error(`Task ${taskId} does not belong to ${id}.`); repo.createCheckpoint({ work_item_id: id, task_id: taskId, summary: options.summary, files: options.files ?? null, decisions: options.decisions ?? null, unresolved_issue: options.unresolvedIssue ?? null, next_step: options.nextStep ?? null }); } finally { repo.close(); } sync(status, id); console.log(`Checkpoint saved for ${id}.`); }));

const knowledge = program.command("knowledge");
knowledge.command("add").requiredOption("--type <type>").requiredOption("--title <title>").requiredOption("--content <content>").option("--work <workId>").option("--topic <topic>").action((options: { type: "decision" | "architecture" | "discovery" | "pattern"; title: string; content: string; work?: string; topic?: string }) => action(() => { if (!["decision", "architecture", "discovery", "pattern"].includes(options.type)) throw new Error("Knowledge type is invalid."); const status = workspace(); const repo = openRepository(status.databasePath); try { const item = repo.createKnowledge({ type: options.type, title: options.title, content: options.content, work_item_id: options.work?.toUpperCase() ?? null, topic_key: options.topic ?? null }); console.log(`Knowledge ${item.id} recorded.`); } finally { repo.close(); } }));
knowledge.command("search").argument("<query>").action((query: string) => action(() => { const status = workspace(); const repo = openRepository(status.databasePath); try { for (const item of repo.searchKnowledge(query)) console.log(`${item.id}: ${item.title} [${item.type}]`); } finally { repo.close(); } }));
knowledge.command("show").argument("<id>").action((id: string) => action(() => { const status = workspace(); const repo = openRepository(status.databasePath); try { const item = repo.getKnowledge(Number(id)); if (!item) throw new Error(`Knowledge ${id} not found.`); console.log(`${item.id}: ${item.title}\n\n${item.content}`); } finally { repo.close(); } }));

program.command("close").argument("<workId>").requiredOption("--message <message>").action((workId: string, options: { message: string }) => action(() => closeWork(workId, options.message)));
function completeTask(taskId: string, options: { evidence: string; files: string[] }, blocked: boolean) { void blocked; const status = workspace(); const id = taskId.toUpperCase(); const repo = openRepository(status.databasePath); let workId: string; try { const entry = repo.getTask(id); if (!entry || entry.status !== "active") throw new Error(`Task ${id} must be active.`); const workItem = repo.getWork(entry.work_item_id)!; const baseline = JSON.parse(workItem.git_baseline_json ?? "null") as { dirty: Array<{ path: string }> } | null; if (!baseline) throw new Error("Task completion requires an activation Git baseline."); const paths = [...new Set(options.files.map((path) => validatePath(status.repoRoot, path)))].sort(); const baselinePaths = new Set(baseline.dirty.map((item) => item.path)); const attribution: Attribution = { paths: paths.map((path) => fileState(status.repoRoot, path)), ambiguousBaselinePaths: paths.filter((path) => baselinePaths.has(path)) }; repo.updateTask(id, { status: "done", validation_evidence: options.evidence.trim(), attribution_json: JSON.stringify(attribution) }); workId = entry.work_item_id; } finally { repo.close(); } sync(status, workId!); console.log(`Completed ${id}.`); }
function closeWork(workId: string, message: string) { const status = workspace(); const id = workId.toUpperCase(); const repo = openRepository(status.databasePath); try { const item = repo.getWork(id); if (!item || item.status !== "review") throw new Error(`Work Item ${id} is not ready to close.`); if (repo.latestReview(id)?.outcome !== "PASS" || !item.validation_evidence) throw new Error("Close requires the latest Work Review PASS and validation evidence."); const baseline = JSON.parse(item.git_baseline_json ?? "null") as { head: string; dirty: Array<{ path: string; state: string; hash: string | null }> } | null; if (!baseline) throw new Error("Close requires an activation Git baseline."); const tasks = repo.listTasks(id) as Task[]; if (tasks.some((entry: Task) => entry.status !== "done")) throw new Error("Close requires all Tasks done."); const attributed = new Map<string, { state: string; hash: string | null }>(); const ambiguous: string[] = []; for (const entry of tasks) { const attribution = entry.attribution_json ? JSON.parse(entry.attribution_json) as Attribution : null; for (const path of attribution?.paths ?? []) attributed.set(path.path, path); ambiguous.push(...(attribution?.ambiguousBaselinePaths ?? [])); } if (ambiguous.length) throw new Error(`Close blocked: baseline-dirty paths cannot be attributed safely: ${[...new Set(ambiguous)].join(", ")}`); for (const original of baseline.dirty) { const actual = fileState(status.repoRoot, original.path); if (actual.state !== original.state || actual.hash !== original.hash) throw new Error(`Close blocked: baseline-dirty path changed: ${original.path}`); } const baselinePaths = new Set(baseline.dirty.map((entry) => entry.path)); const finalPaths = changedPaths(status.repoRoot, baseline.head); const workPaths = finalPaths.filter((path) => !baselinePaths.has(path)); const unowned = workPaths.filter((path) => !attributed.has(path)); if (unowned.length) throw new Error(`Close blocked: unattributed changed paths: ${unowned.join(", ")}`); for (const [path, expected] of attributed) { const actual = fileState(status.repoRoot, path); if (actual.state !== expected.state || actual.hash !== expected.hash) throw new Error(`Close blocked: ${path} changed after Task attribution.`); } const alreadyStaged = cachedPaths(status.repoRoot); if (alreadyStaged.length && JSON.stringify(alreadyStaged) !== JSON.stringify(workPaths.sort())) throw new Error("Close blocked: staged changes do not exactly match Work Item changes."); if (!alreadyStaged.length) stage(status.repoRoot, workPaths); console.log(stagedDiff(status.repoRoot) || "No staged diff."); const hash = commit(status.repoRoot, `${message}\n\nNerv-Work: ${id}`); repo.updateWork(id, { status: "closed", closed_at: new Date().toISOString(), commit_hash: hash }); removeActiveContext(status.workspaceRoot, id); console.log(`Closed ${id}: ${hash}`); } finally { repo.close(); } }

program.command("status").description("Show workspace and context availability.").action(() => action(() => { const status = getWorkspaceStatus(process.cwd()); console.log(`Nerv status: ${status.initialized ? "initialized" : "not initialized"}`); if (status.initialized && status.workspaceRoot && status.databasePath) { const context = discoverContext(status.workspaceRoot, status.databasePath); console.log(`Product Context: ${context.product.length ? "available" : "not available"}`); console.log(`Repo Context: ${context.repo ? "available" : "not available"}`); } }));
await program.parseAsync();
