import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const PACKAGE_CONFIG_FILES = [
  "package.json",
  "tsconfig.json",
  "tsconfig.*.json",
  ".eslintrc",
  ".eslintrc.json",
  ".eslintrc.js",
  "eslint.config.js",
  "eslint.config.mjs",
  ".prettierrc",
  ".prettierrc.json",
  "prettier.config.js",
  "prettier.config.mjs",
  ".gitignore",
  ".npmrc",
  ".nvmrc",
  "Dockerfile",
  "docker-compose.yml",
  "docker-compose.yaml",
  "README.md",
  "LICENSE",
] as const;

export type RepoAnalysis = {
  packageFiles: string[];
  scripts: Record<string, string>;
  topLevelFolders: string[];
  gitStatus: string | null;
  gitAvailable: boolean;
};

export function analyzeRepo(repoRoot: string): RepoAnalysis {
  const packageFiles = detectPackageFiles(repoRoot);
  const scripts = extractScripts(repoRoot);
  const topLevelFolders = getTopLevelFolders(repoRoot);
  const gitInfo = getGitInfo(repoRoot);

  return {
    packageFiles,
    scripts,
    topLevelFolders,
    gitStatus: gitInfo.status,
    gitAvailable: gitInfo.available,
  };
}

function detectPackageFiles(repoRoot: string): string[] {
  const found = new Set<string>();

  for (const pattern of PACKAGE_CONFIG_FILES) {
    if (pattern.includes("*")) {
      const prefix = pattern.split("*")[0];
      const suffix = pattern.split("*")[1];

      try {
        const files = readdirSync(repoRoot);
        for (const file of files) {
          if (file.startsWith(prefix) && file.endsWith(suffix)) {
            found.add(file);
          }
        }
      } catch {
        // Directory read failed, skip
      }
    } else {
      if (existsSync(join(repoRoot, pattern))) {
        found.add(pattern);
      }
    }
  }

  return Array.from(found).sort();
}

function extractScripts(repoRoot: string): Record<string, string> {
  const packageJsonPath = join(repoRoot, "package.json");

  if (!existsSync(packageJsonPath)) {
    return {};
  }

  try {
    const content = readFileSync(packageJsonPath, "utf8");
    const pkg = JSON.parse(content);

    if (pkg.scripts && typeof pkg.scripts === "object") {
      return pkg.scripts;
    }
  } catch {
    // Failed to parse package.json
  }

  return {};
}

function getTopLevelFolders(repoRoot: string): string[] {
  const folders: string[] = [];

  try {
    const entries = readdirSync(repoRoot);

    for (const entry of entries) {
      if (entry.startsWith(".") || entry === "node_modules") {
        continue;
      }

      const fullPath = join(repoRoot, entry);

      try {
        const stat = statSync(fullPath);
        if (stat.isDirectory()) {
          folders.push(entry);
        }
      } catch {
        // Can't stat this entry, skip
      }
    }
  } catch {
    // Directory read failed
  }

  return folders.sort();
}

function getGitInfo(repoRoot: string): { status: string | null; available: boolean } {
  const gitDir = join(repoRoot, ".git");

  if (!existsSync(gitDir)) {
    return { status: null, available: false };
  }

  try {
    const result = spawnSync("git", ["status", "--short"], {
      cwd: repoRoot,
      encoding: "utf8",
      timeout: 5000,
    });

    if (result.status === 0) {
      const output = result.stdout.trim();
      return { status: output || "clean", available: true };
    }
  } catch {
    // Git command failed
  }

  return { status: null, available: true };
}

export function generateDevelopmentDoc(analysis: RepoAnalysis): string {
  const lines: string[] = [];

  lines.push("# Development Context");
  lines.push("");
  lines.push("This document is auto-generated by `nerv repo`. It provides lightweight repo awareness for agent runs.");
  lines.push("");

  // Package and config files
  lines.push("## Package and Config Files");
  lines.push("");
  if (analysis.packageFiles.length === 0) {
    lines.push("No common package or config files detected.");
  } else {
    for (const file of analysis.packageFiles) {
      lines.push(`- \`${file}\``);
    }
  }
  lines.push("");

  // Scripts
  lines.push("## Scripts");
  lines.push("");
  const scriptEntries = Object.entries(analysis.scripts);
  if (scriptEntries.length === 0) {
    lines.push("No scripts detected.");
  } else {
    for (const [name, command] of scriptEntries) {
      lines.push(`- \`${name}\`: \`${command}\``);
    }
  }
  lines.push("");

  // Validation commands
  lines.push("## Validation Commands");
  lines.push("");
  const validationScripts = scriptEntries.filter(([name]) =>
    ["test", "lint", "typecheck", "build", "check"].includes(name),
  );
  if (validationScripts.length === 0) {
    lines.push("No standard validation scripts detected.");
  } else {
    lines.push("Run these commands to validate changes:");
    lines.push("");
    for (const [name] of validationScripts) {
      lines.push(`- \`${name}\``);
    }
  }
  lines.push("");

  // Top-level folders
  lines.push("## Top-Level Folders");
  lines.push("");
  if (analysis.topLevelFolders.length === 0) {
    lines.push("No top-level folders detected.");
  } else {
    for (const folder of analysis.topLevelFolders) {
      lines.push(`- \`${folder}/\``);
    }
  }
  lines.push("");

  // Git status
  lines.push("## Git Status");
  lines.push("");
  if (!analysis.gitAvailable) {
    lines.push("Not a Git repository or Git is not available.");
  } else if (analysis.gitStatus === null) {
    lines.push("Git status unavailable.");
  } else if (analysis.gitStatus === "clean") {
    lines.push("Working tree is clean.");
  } else {
    lines.push("Working tree has changes:");
    lines.push("");
    lines.push("```");
    lines.push(analysis.gitStatus);
    lines.push("```");
  }
  lines.push("");

  return lines.join("\n");
}
