import { randomUUID } from "node:crypto";
import Database from "better-sqlite3";

export type WorkStatus = "active" | "review" | "rework" | "closed";
export type TaskStatus = "pending" | "active" | "done" | "blocked";
export type WorkItem = { id: string; ref: string; title: string; status: WorkStatus; intent: string; goal: string; scope: string; expected_touchpoints: string; out_of_scope: string; acceptance_criteria: string; validation: string; validation_evidence: string | null; git_baseline_json: string | null; created_at: string; updated_at: string; closed_at: string | null; commit_hash: string | null };
export type Task = { id: string; work_item_id: string; position: number; title: string; status: TaskStatus; objective: string; implementation_approach: string; expected_touchpoints: string; acceptance_criteria: string; validation: string; validation_evidence: string | null; block_reason: string | null; attribution_json: string | null; created_at: string; updated_at: string };
export type PlanTask = Pick<Task, "title" | "objective" | "implementation_approach" | "expected_touchpoints" | "acceptance_criteria" | "validation">;
export type ApprovedPlan = Pick<WorkItem, "title" | "intent" | "goal" | "scope" | "expected_touchpoints" | "out_of_scope" | "acceptance_criteria" | "validation"> & { tasks: PlanTask[]; git_baseline_json: string };
export type Review = { id: number; work_item_id: string; outcome: "PASS" | "REWORK"; summary: string; findings: string | null; validation_evidence: string; created_at: string };
export type Checkpoint = { id: number; work_item_id: string; task_id: string | null; summary: string; files: string | null; decisions: string | null; unresolved_issue: string | null; next_step: string | null; created_at: string };
export type Attribution = { paths: Array<{ path: string; state: "present" | "deleted"; hash: string | null }>; ambiguousBaselinePaths?: string[] };
const now = () => new Date().toISOString();

export function openRepository(path: string): any {
  const db = new Database(path); db.pragma("journal_mode = WAL"); db.pragma("foreign_keys = ON");
  const nextWorkRef = () => { const stored = db.prepare("SELECT value FROM metadata WHERE key = 'next_work_number'").get() as { value: string } | undefined; const value = Number(stored?.value) || 1; db.prepare("INSERT INTO metadata (key,value,updated_at) VALUES ('next_work_number',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").run(String(value + 1), now()); return `WORK-${String(value).padStart(3, "0")}`; };
  const getWork = (idOrRef: string) => (db.prepare("SELECT * FROM work_items WHERE id = ? OR ref = ?").get(idOrRef, idOrRef) as WorkItem | undefined) ?? null;
  const getTask = (id: string) => (db.prepare("SELECT * FROM tasks WHERE id = ?").get(id) as Task | undefined) ?? null;
  const updateWork = (id: string, changes: Partial<WorkItem>) => { const current = getWork(id); if (!current) throw new Error(`Work Item ${id} not found.`); db.prepare("UPDATE work_items SET title=@title,status=@status,intent=@intent,goal=@goal,scope=@scope,expected_touchpoints=@expected_touchpoints,out_of_scope=@out_of_scope,acceptance_criteria=@acceptance_criteria,validation=@validation,validation_evidence=@validation_evidence,git_baseline_json=@git_baseline_json,updated_at=@updated_at,closed_at=@closed_at,commit_hash=@commit_hash WHERE id=@id").run({ ...current, ...changes, id, updated_at: now() }); };
  const updateTask = (id: string, changes: Partial<Task>) => { const current = getTask(id); if (!current) throw new Error(`Task not found.`); db.prepare("UPDATE tasks SET status=@status,objective=@objective,implementation_approach=@implementation_approach,expected_touchpoints=@expected_touchpoints,acceptance_criteria=@acceptance_criteria,validation=@validation,validation_evidence=@validation_evidence,block_reason=@block_reason,attribution_json=@attribution_json,updated_at=@updated_at WHERE id=@id").run({ ...current, ...changes, id, updated_at: now() }); };
  const materializePlan = db.transaction((plan: ApprovedPlan) => { if (!plan.tasks.length) throw new Error("An approved Work plan requires at least one Task."); const timestamp = now(); const item: WorkItem = { ...plan, id: randomUUID(), ref: nextWorkRef(), status: "active", validation_evidence: null, created_at: timestamp, updated_at: timestamp, closed_at: null, commit_hash: null }; db.prepare("INSERT INTO work_items VALUES (@id,@ref,@title,@status,@intent,@goal,@scope,@expected_touchpoints,@out_of_scope,@acceptance_criteria,@validation,@validation_evidence,@git_baseline_json,@created_at,@updated_at,@closed_at,@commit_hash)").run(item); const insert = db.prepare("INSERT INTO tasks VALUES (@id,@work_item_id,@position,@title,@status,@objective,@implementation_approach,@expected_touchpoints,@acceptance_criteria,@validation,@validation_evidence,@block_reason,@attribution_json,@created_at,@updated_at)"); plan.tasks.forEach((input, index) => insert.run({ ...input, id: randomUUID(), work_item_id: item.id, position: index + 1, status: "pending", validation_evidence: null, block_reason: null, attribution_json: null, created_at: timestamp, updated_at: timestamp })); return item; });
  const materializeRework = db.transaction((workId: string, tasks: PlanTask[]) => { const item = getWork(workId); if (!item || item.status !== "rework") throw new Error("Approved remediation requires a Work Item in rework."); if (!tasks.length) throw new Error("Approved remediation requires at least one Task."); const timestamp = now(); const first = (db.prepare("SELECT COALESCE(MAX(position), 0) AS position FROM tasks WHERE work_item_id = ?").get(item.id) as { position: number }).position + 1; const insert = db.prepare("INSERT INTO tasks VALUES (@id,@work_item_id,@position,@title,@status,@objective,@implementation_approach,@expected_touchpoints,@acceptance_criteria,@validation,@validation_evidence,@block_reason,@attribution_json,@created_at,@updated_at)"); tasks.forEach((input, index) => insert.run({ ...input, id: randomUUID(), work_item_id: item.id, position: first + index, status: "pending", validation_evidence: null, block_reason: null, attribution_json: null, created_at: timestamp, updated_at: timestamp })); updateWork(item.id, { status: "active" }); return getWork(item.id)!; });
  return { close: () => db.close(), getWork, getTask, updateWork, updateTask, materializePlan, materializeRework, listWork: () => db.prepare("SELECT * FROM work_items ORDER BY ref").all() as WorkItem[], listTasks: (workId: string) => db.prepare("SELECT * FROM tasks WHERE work_item_id = ? ORDER BY position").all(workId) as Task[], getTaskAt: (workId: string, position: number) => (db.prepare("SELECT * FROM tasks WHERE work_item_id = ? AND position = ?").get(workId, position) as Task | undefined) ?? null, createReview(input: Omit<Review, "id" | "created_at">) { const result = db.prepare("INSERT INTO work_reviews (work_item_id,outcome,summary,findings,validation_evidence,created_at) VALUES (?,?,?,?,?,?)").run(input.work_item_id,input.outcome,input.summary,input.findings,input.validation_evidence,now()); return db.prepare("SELECT * FROM work_reviews WHERE id=?").get(result.lastInsertRowid) as Review; }, listReviews: (workId: string) => db.prepare("SELECT * FROM work_reviews WHERE work_item_id=? ORDER BY id").all(workId) as Review[], latestReview: (workId: string) => (db.prepare("SELECT * FROM work_reviews WHERE work_item_id=? ORDER BY id DESC LIMIT 1").get(workId) as Review | undefined) ?? null, createCheckpoint(input: Omit<Checkpoint, "id" | "created_at">) { const result = db.prepare("INSERT INTO checkpoints (work_item_id,task_id,summary,files,decisions,unresolved_issue,next_step,created_at) VALUES (?,?,?,?,?,?,?,?)").run(input.work_item_id,input.task_id,input.summary,input.files,input.decisions,input.unresolved_issue,input.next_step,now()); return db.prepare("SELECT * FROM checkpoints WHERE id=?").get(result.lastInsertRowid) as Checkpoint; }, latestCheckpoint: (workId: string) => (db.prepare("SELECT * FROM checkpoints WHERE work_item_id=? ORDER BY id DESC LIMIT 1").get(workId) as Checkpoint | undefined) ?? null, getMetadata: (key: string) => (db.prepare("SELECT value FROM metadata WHERE key=?").get(key) as { value: string } | undefined)?.value ?? null, setMetadata: (key: string, value: string) => db.prepare("INSERT INTO metadata (key,value,updated_at) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").run(key,value,now()) };
}
